name: cellcap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipykernel
  - h5py
  - anndata
  - scanpy
  - scvi-tools
  - pytorch::pytorch
  - pytorch::torchvision
  - pip:
      - cellcap
      - gdown
      - tqdm
      - pyyaml
