name: gears
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - jupyter
  - jupyterlab
  - ipykernel
  - h5py
  - anndata
  - scanpy
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
      - cell-gears
      - torch-geometric
      - goatools
      - obonet
      - tqdm
      - pyyaml
